### ISSUE TITLE
[Help][Blog] Adding comments using staticman

### ISSUE THREAD

**Issue by friyaz** [gabeluci/gabeluci.github.io#93]
Thank you very much for writing the blog post on adding comments using staticman. 

I followed all the steps. Everything is working except the comments are not getting displayed. Only the number of comments is shown.

Link to my blog: https://friyaz.github.io
My template: https://github.com/friyaz/portfolYOU

**Comment by gabeluci** [comment]
Looks like you got it figured out?

**Comment by friyaz** [comment]
Thanks for replying @gabeluci . Comments are displayed when the condition for determining top order comments is removed.
```
    {% assign comments = site.data.comments[page.slug] | sort | where_exp: 'comment', 'comment[1]._parent == comment[1]._id' %}
```
```
    {% assign comments = site.data.comments[page.slug] | sort}

**Comment by friyaz** [comment]
I think I have figured out the problem. My comments somehow do not get _parent field value.
```
_id: cae2f320-9288-11ea-b651-7136043d35c4
name: abcd
email: 46040c38d1cbe8ffcd3df6c8ba787951
url: ''
message: random reply
date: 1589092680
```
This line should have set the parent option to the replying comment id.
```
      <input type="hidden" id="comment-replying-to" name="options[parent]" value>
```

**Comment by gabeluci** [comment]
Thanks for noticing the missing `</div>`. I fixed that.

About the missing `_parent` value: if you're talking about the top-level comments, it is because I changed the Staticman code to set that for top-level comments (because I'm running my own instance of Staticman). Read the "Per-Thread Notifications" section here: https://www.gabescode.com/staticman/2019/01/04/staticman-comments-for-jekyll.html#per-thread-notifications

**Comment by friyaz** [comment]
Thanks for looking into this. I forked your repo of static man and deployed it on Heroku. Still no luck.

**Comment by friyaz** [comment]
It is working [now](https://friyaz.github.io/blog/testing-jekyll)!

I forked staticman from eduardoboucas. In the `_applyInternalFields` function, I added 
```javascript
      if (!this.options.parent) {
        this.options.parent = this.uid
      }
```
The javascript for displaying sucess message is also working. It turned out that `main.js` was not included in `scripts.html`.

Thanks again for your help.

**Comment by andyfry01** [comment]
Your fix worked for me to @friyaz, thanks for making an issue so the rest of us can debug!

**Comment by gabeluci** [comment]
@andyfry01 Thanks for the kind words. I'm glad it could help!
